### ISSUE TITLE
403 error in access denied views

### ISSUE THREAD

**Issue by jayesh92** [systers/vms#119]
I was writing tests as I found that for many views like `shift/view_volunteer_shifts` in cases where one volunteer tries to access another volunteer's shifts, It raises a 403 error due the code on https://github.com/systers/vms/blob/develop/vms/shift/views.py#L598 . What this does this is that it just sets-up a 403 status code in response header and the user gets a blank page and status code can be seen if we open the console.
Shouldn't we be sending a proper Access Denied page instead of just the error code ?

**Comment by jayesh92** [comment]
I've been able to test it manually, I can't get the response status code in selenium, same has also been a concern of few others at this stackoverflow [answer](http://stackoverflow.com/questions/6509628/how-to-get-http-response-code-using-selenium-webdriver-with-java)

**Comment by willingc** [comment]
@jayesh92 Is there a link to the tests that you are running?

**Comment by jayesh92** [comment]
@willingc , https://github.com/jayesh92/vms/blob/master/vms/shift/tests/test_viewVolunteerShift.py#L57
As I've stated above, I can't get the return status code using selenium, so it's not a complete test. However, If you can repro this use-case, you'll get a blank page instead of a page showing 403. Something like this is done in the test just below the one which I've linked

**Comment by smarshy** [comment]
@tapasweni-pathak I agree with Jayesh on this. It may be better to display a no rights page similar to the way no admin rights is displayed now in case of unauthorized access to admin views. A couple of test situations (A volunteer accessing another volunteer's view and an admin accessing a volunteer view) are failing due to this.

**Comment by tapasweni-pathak** [comment]
@smarshy Sure. Please go ahead and raise an issue. I'll tag it as enhancement. After this I'll close this.

One more thing, it is fine if admin accesses a volunteer view. Volunteer accessing other volunteer's view is not correct.

**Comment by smarshy** [comment]
@tapasweni-pathak Is it okay then for the admin to access all volunteer pages - list sign up, volunteer profile, report? Because right now, the  following events happen when the admin tries to access volunteer pages-
_/shift/view_volunteer_shifts/1_  -  Blank page displayed
_/shift/view_hours/1_                  -  Error page shows up
_/event/list_sign_up/1_               -  Sign up page shows properly, admin can access without any errors
_/volunteer/report/1_                  -  Error page shows up
_/volunteer/profile/1_                  -  Error page shows up

The error page shows up as the user has no volunteer and related object is not existing. Shouldn't there be a no rights page in those cases?

**Comment by tapasweni-pathak** [comment]
@willingc @vubo @Nerdylicious @rosariorobinson What should be the ideal behavior here?

**Comment by anjali-dhanuka** [comment]
Please use the issue template
