### ISSUE TITLE
SHIFT SIGN UP list enchancement: show only not empty events and jobs

### ISSUE THREAD

**Issue by vubo** [systers/vms#175]
In the "SHIFT SIGN UP" list we can see all jobs and events. Even events and jobs without shifts. Show only not empty events and jobs.

![image](https://cloud.githubusercontent.com/assets/7673323/11836436/02fa2586-a3db-11e5-9cd3-8bf51549da21.png)

**Comment by ahmedsabie** [comment]
Hey Valeria! Here is the pull request for this issue: https://github.com/systers/vms/pull/176

**Comment by tapasweni-pathak** [comment]
@ahmedsabie You can reference the issue in the pull request with something like "closes #number_of_the_issue.".  This will automatically link your PR to the issue.

**Comment by ahmedsabie** [comment]
@tapasweni-pathak thanks a lot for the tip! Added to the PR.

**Comment by KokareIITP** [comment]
@vubo @tapasweni-pathak 
Please review the pull request. 
https://github.com/systers/vms/pull/180

**Comment by tapasweni-pathak** [comment]
@KokareIITP Thank for your work but this issue is for GCI participants. We would be constraining our contributors to not contribute to GCI issues for a while, as we are getting duplicate work for many. 

As I suggested previously, avoid commenting on issues about things which are not relevant to know more about a issue. For every new PR we get a notification and the best way to reference a issue is in the PR description using *closes #number_of_the_issue*.
