### ISSUE TITLE
Add missing unit tests

### ISSUE THREAD

**Issue by vubo** [systers/vms#29]
- [x] Add missing unit tests in organization/tests.py
- [x] Add missing unit tests in event/tests.py
- [x] Add missing unit tests in job/tests.py
- [x] Add missing unit tests in shift/tests.py
- [x] Add missing unit tests in volunteer/tests.py

**Comment by vubo** [comment]
Add missing unit tests in organization/tests.py https://github.com/systers/vms/pull/28

**Comment by willingc** [comment]
I like this!

GitHub tip: You can make checkboxes using GitHub markdown. Check out https://guides.github.com/features/mastering-markdown/ in the Task Lists section.

**Comment by vubo** [comment]
It looks very cool, thank you!
![tasks](https://cloud.githubusercontent.com/assets/7673323/7995930/555c7256-0b1b-11e5-95c6-1845fe8cbfdd.png)

**Comment by willingc** [comment]
Nice. It is pretty cool :)

**Comment by jayesh92** [comment]
@willingc @vubo Would It be a good idea to include the functional tests in this repo or should I include it in AUT repo. Benefit in first case is that I can integrate it with CI so all new code pushed passes throught these tests also.
I'm currently doing this on my local instance. For this we'll need to change the directory structure a bit. Instead of `tests.py` each app will contain a `tests` folder and an `__init__.py` . All tests need to be put up in this folder namely, unit-tests and functional tests.
Your views ? The respective commit for this can be seen in my fork https://github.com/jayesh92/vms/commit/d7b5d939050141e539b475a3231efaff26593854 and directory structure at https://github.com/jayesh92/vms/tree/master/vms/home

**Comment by willingc** [comment]
Hmm...good questions. Nice job asking for thoughts and feedback. 
I'm not yet sure what would be best. I would like to clarify with the other team members what their vision is longer term related to:
* Python version support 2.7.10 or 3.4+ 
* Django version support - recommend 1.8LTS

Would you both raise these questions on your weekly reports for discussion? It looks like Systers/portal is already using Python 3.4 and Django 1.7.7. I would recommend that VMS match their Django infrastructure, but this really is a discussion for a larger audience :)

Please feel free to continue discussing thoughts or ideas here too.

**Comment by vubo** [comment]
Add missing unit tests in event/tests.py: https://github.com/systers/vms/pull/36

**Comment by vubo** [comment]
Add missing unit tests in job/tests.py: https://github.com/systers/vms/pull/38

**Comment by willingc** [comment]
@vubo You are making good progress on this issue. Let's try to get the remaining two done this week. I'll do a detailed review this weekend.

You may wish to do a quick skim of coverage.py docs, tox, and some of Harry Percival's Test Driven Development book (http://obeythetestinggoat.com). We'll likely use all of these when adding new features.

**Comment by vubo** [comment]
@willingc yes, I will finish the tests before Sunday then.

**Comment by vubo** [comment]
Add missing unit tests in shift/tests.py: https://github.com/systers/vms/pull/43

**Comment by vubo** [comment]
Add missing unit tests in volunteer/tests.py: https://github.com/systers/vms/pull/47
