### ISSUE TITLE
Create event, start date should be later than today.

### ISSUE THREAD

**Issue by shoaib-s** [systers/vms#299]
I can create an event with yesterday's date. This issue is similar to #263 , #263 has same problem when user tries to edit the date of event. Created new issue to keep create event problem separate. I am working on this issue.

**Comment by smarshy** [comment]
@tapasweni-pathak This issue still exists and I am able to replicate it. But before this is changed, can it be clarified as to why the buffer of 1 day was taken initially? Was this done to handle timezones and because people might be moving one day ahead from those in other regions?

**Comment by shoaib1987** [comment]
@smarshy yes, it still exists. Buffer of 1 day was taken initially to handle timezone issue but I don't think that's the right way to handle it. In this case user can be anywhere in the world and can create an event for any other location. I believe user should be able to select a valid date as per the venue(country, city) selected by user. I know 2 ways to implement this, 1.find the timezone based on a country and a city entered by user(this will be little challenging for various practical reasons) 2. provide drop down list to user to select a country and a city to set the specific timezone. Please let me know what do you think?

**Comment by smarshy** [comment]
@shoaib-s So effectively, I think the suggestion here is that instead of the date being compared to date as per the user's computer, it would be compared to the date in the location that is being selected. Have I understood that properly?
It seems to be a sensible thing to do, especially if this was the only reason why the buffer was set. However there are challenges here as to doing that - 
1. The country/state/venue fields are not compulsory. If a user doesn't set that, how would the logic flow be in that situation?
2. The location fields are not being validated currently at all, so then there is a possibility of non-existent locations being entered.
3. Editing is allowed so later these venues might be changed. Are the dates validated again then?
4. Basic task at hand - How would the dates be checked if there is a location entered? Do you have a logic flow or packages in mind which could help out with this?

Right now date is checked against the date on the computer. There is no timezone handling. Keeping a buffer of 1 day is an easier hack to these steps though I am not very sure as to if that is the right way. Let others too put in their views on this :)

@tapasweni-pathak Please let us know your thoughts on this.

**Comment by shoaib-s** [comment]
@smarshy  Yes, you got it.
I do not see any other reason for which buffer was set.
WRT to challenges you discussed:
1. I think these fields should be mandatory. I do not see a reason for which they should not be mandatory. An event without venue details doesn't seems to be very realistic in this scenario, please let me know if I am missing anything.
2. Yes, and it's challenging to find timezones of specific locations provided by user(more details in point 4). What if user sees the drop down list of locations to select(country, state and city)?
3. Function edit(request, event_id) in event/views.py gets called when button "save" is clicked on edit form, it performs date validation check. However, this logic should be changed to compare the date in the location that is being selected.
4. 
Approach 1: 
Select location from drop down list. Find timezone using pytz, drop-down list provided must match to pytz list of locations. pytz does not contain data to map an arbitrary city in the world to the timezone. 
Approach 2:
User will enter the location, drop down list is not provided. In this case we need a geocoder such as geopy that can translate a place (e.g., a city name) to its coordinates (latitude, longitude), given city's latitude, longitude, it is possible to find its timezone.
Following 2 links seems to be helpful:
https://docs.djangoproject.com/en/1.9/topics/i18n/timezones/
http://stackoverflow.com/questions/16505501/get-timezone-from-city-in-python-django

**Comment by tapasweni-pathak** [comment]
@shoaib-s Feel free to submit a pull request for the same.

**Comment by anjali-dhanuka** [comment]
@tapasweni-pathak This one has been implemented. We can close the issue.

**Comment by ayushgarg1804** [comment]
@anjali-dhanuka can you please comment the commit # where this was implemented.

**Comment by anjali-dhanuka** [comment]
Here it is 
https://github.com/systers/vms/commit/179b8ebc896862a378c641346c5996abd7751fe1
