### ISSUE TITLE
Volunteer should not be able to access another volunteer's url

### ISSUE THREAD

**Issue by smarshy** [systers/vms#326]
The following events happen when a volunteer tries to access another volunteer's url using their id -

_/shift/view_volunteer_shifts/id_  -  Blank page shows up
_/shift/view_hours/id_  -  Blank page shows up
_/event/list_sign_up/id_ - volunteer is able to access
_/volunteer/report/id_  - Blank page shows up
_/volunteer/profile/id_  - Blank page shows up

To avoid blank/error pages and since error codes are difficult to detect as pointed out in #119 , it would maybe be better to show a no volunteers right page for that volunteer

**Comment by smarshy** [comment]
@tapasweni-pathak Should the administrator be able to view these pages? If they are able to view it, it means that they can modify any volunteer's profile, hours, sign up for events etc without their consent.

**Comment by InfernoCoder** [comment]
While doing this task - Volunteer should not be able to access another volunteer's url, I have noticed that there are some more urls like `/volunteer/edit/`, ` volunteer/add_hours/`, `volunteer/edit_hours/` etc can also be accessed by others, but are not mentioned in the issue list. And for the `shift/cancel/` one, when it is accessed by non-authorized people, it shows an Http 403 page, instead of the normal "no rights" page. I'm fixing this in my PR.

**Comment by anjali-dhanuka** [comment]
@tapasweni-pathak This one is done! It can be closed.

**Comment by MeepyMay** [comment]
PR Merged. Closing Issue.
