### ISSUE TITLE
Unable to create database vms 

### ISSUE THREAD

**Issue by swekshajha12** [systers/vms#464]
While trying to create the database vms with user as vmsadmin by executing the following command
createdb -U vmsadmin vms;
The following error comes:
createdb: couldn't connect to database template1: FATAL: peer authentication failed for user "vmsaddmin"
![sys2](https://user-images.githubusercontent.com/22135941/31278653-6f5f03a4-aac3-11e7-8169-061b245c6a17.png)

**Comment by Godsownchild** [comment]
You need to change the pg_hba.conf  file to indicate that users will authenticate by md5 as opposed to peer authentication. To do this, first open the pg_hba.conf  file by running the command:
 sudo nano /etc/postgresql/9.6/main/pg_hba.conf
depending on the version of postgresql mine is 9.6

or

 You may need to open pg_hba.conf with your text editor  because I had the same issues and this worked for me.

Change the line local all postgres peer to local all postgres md5

Also, change the line local all all peer to local all all md5

**Comment by Godsownchild** [comment]
You can use gedit 

sudo -H gedit /etc/postgresql/9.6/main/pg_hba.conf
It is a configuration file you can't open it directly. Or read this to https://askubuntu.com/questions/438524/how-can-i-edit-the-lightdm-conf-file-and-save-it understand better.I hope this works for you

**Comment by swekshajha12** [comment]
Hey! Thanks but I have already done that , since they are the initial steps. This isssue persists.

**Comment by tapasweni-pathak** [comment]
@swekshajha12 Please update this issue with how did you fix the errors. Thanks!

**Comment by swekshajha12** [comment]
There were some discrepancies with my pg_hba.conf file and thus did the whole process again and edited the pg_hba.conf file . This solved the error.
