### ISSUE TITLE
username unique field, not email

### ISSUE THREAD

**Issue by jayesh92** [systers/vms#48]
- while writing tests, I've found that unique parameter used is `username` and not email
- I'm able to register more than one volunteers with same email but different usernames.

Should it be like this ?
@willingc @vubo

**Comment by willingc** [comment]
@Nerdylicious @rosariorobinson @tapasweni-pathak Please add any history on what is the unique user identification parameter or the desired unique identifier.

@jayesh92, @vubo My understanding is the project uses `django.contrib.auth.models` User objects.

`django.contrib.auth.models` uses username as a required identifier unless overridden as a custom user model.
https://docs.djangoproject.com/en/1.8/topics/auth/default/
https://docs.djangoproject.com/en/1.8/ref/contrib/auth/#django.contrib.auth.models.User

Overall, it probably makes sense for this to have better documentation of the model:
https://github.com/systers/vms/blob/0190b907673f638c21ef3bc1673bfcc3c1a4735e/vms/volunteer/models.py#L102

**Comment by tapasweni-pathak** [comment]
@willingc Yes, as the project uses django.contrib.auth.models, the unique identifier is username.

I don't feel it should be like this, every user of vms (volunteers) should have a unique username and email id. Later, if we added some features which uses the uniqueness, it may create a problem.
Once someone registered with a email id and a username, the email id should not be allowed to used again. 


@rosariorobinson @Nerdylicious can suggest better.

**Comment by willingc** [comment]
@tapasweni-pathak While the email can be checked and set as unique, I don't believe that it should be the primary ID of uniqueness for a volunteer. Many people have multiple email addresses and down the road the volunteer management system may have to support a user's multiple contact preferences. 

I think it is best to use the django default of username as the unique identifier since core Django can take care of much of the user checking without having to write our own. 

There should be a check that an email can not be committed to the database if any other user has that email in the database.

**Comment by tapasweni-pathak** [comment]
@willingc I think I was not able to explain myself properly. 

While the uniqueness check should be on the username but the email id should not be allowed to be reused again for some other username. The same thing that you are saying. :+1: 

What I meant with adding some features using this is, if someday we wanted to support search for a volunteer using her/his mail id. One mail id should reference one username and a user can ofcourse have multiple mail ids. From mail id to username, it should be M:1 relationship and M >= 1.

Once someone registered with a email id and a username, the email id should not be allowed to used again. That's why I said it should not be like this, we should have one check on the reuse (not allowed) of email id for different username.

**Comment by willingc** [comment]
@tapasweni-pathak :+1: Yes, we are in agreement. Sorry I didn't understand this from the earlier comment :cake:

**Comment by tapasweni-pathak** [comment]
@willingc :star2:

**Comment by galarnyk** [comment]
Definitely a data model error to allow the same email address for multiple usernames.

**Comment by vubo** [comment]
@jayesh92 thanks for opening an issue.

@willingc @tapasweni-pathak @galarnyk thank you for the discussion and help. I added unique=True to the email field in the PR https://github.com/systers/vms/pull/84

**Comment by tapasweni-pathak** [comment]
I think, now this issue can we closed.
