### ISSUE TITLE
Upcoming Shifts - Shift Hours

### ISSUE THREAD

**Issue by vubo** [systers/vms#71]
@Nerdylicious when you have time, could you explain please the difference between "Upcoming Shifts" and "Shift Hours".

- Why after a volunteer makes "log hours" for a shift, she/he does not see this shift in the "Upcoming Shifts" list?
- If a volunteer does not make "log hours" for a shift, what does that mean?

@jayesh92 perhaps you could also help with this issue?

Thank you!

![upcomingshifts](https://cloud.githubusercontent.com/assets/7673323/8393828/544fc45e-1d21-11e5-81ce-201f1b140eb4.png)

![shifthours](https://cloud.githubusercontent.com/assets/7673323/8393829/59d65a6e-1d21-11e5-819a-896b8e78c7c1.png)

**Comment by Nerdylicious** [comment]
Hi @vubo thanks for the questions!

- A shift moves from the Upcoming Shifts page to the Shift Hours page when they have logged hours for that shift (since the shift is no longer "upcoming" and it has been completed). Maybe Shift Hours should be renamed to something more clear, like "Completed Shifts". Maybe there should be a notification that the shift was moved to "Completed Shifts"? What do you think?
- A volunteer will log hours whenever they have completed a shift. If they have not logged any hours yet, they have either missed this shift or still need to do it.

It does seem quite confusing having these 2 pages. The Upcoming Shifts page is for all shifts that have been signed up for but with hours that still need to be logged. The Shift Hours page is for all shifts that have been signed up for with hours that have been logged. Upcoming Shifts are uncompleted shifts and Shift Hours are completed shifts. It might be less confusing if we renamed it to Upcoming (Uncompleted) Shifts and Completed Shifts.

Also, what happens when a Volunteer misses their shift? What should we do to handle this situation?

**Comment by vubo** [comment]
Thank you for the answers @Nerdylicious 

"Completed Shifts" sounds great and there is no confusion! :+1: 

I would suggest:

1. If a Volunteer did not log her / his hours and a shift was over (we always have a date of the shift), then the button "Log hours" should disappear and another label should appear. For example "Missed" or something else. 
2. The second possibility: just do not show in this list (Upcoming Shifts) past shifts. Now I can see in the list, such as shifts for 2013. Maybe we should skip the past shifts?

What do you think? 1 or 2?

**Comment by Nerdylicious** [comment]
Hi @vubo 

For (1) you have to remember that a volunteer needs to be able to enter in their hours a day, 2 days or even a week after the shift is over (there are some volunteers that may take a few days to enter in their hours, they don't do it right away).

I would ask @rosariorobinson what she wants, since she's the client.
