### ISSUE TITLE
Resume upload is not working on travis

### ISSUE THREAD

**Issue by Monal5031** [systers/vms#776]
## Description
Resume upload method used in `test_volunteerProfile` is taking too long on travis, this issue needs more digging in the bug.

## Mocks
N/A, This can be checked in the logs of volunteer tests, the next statement is failing with `StaleElementException` which is explicit WebDriverWait for profile implying the profile is not being refreshed after upload.

### Update [Required]
- [ ] Find solution to this issue and fix the 2 failing tests which upload resume.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 2 mentors.

## Estimation
No idea!

**Comment by muskan6769** [comment]
@Monal5031 Can I take up this issue?

**Comment by Monal5031** [comment]
Sure GFI :+1: @muskan6769

**Comment by Monal5031** [comment]
Last I dug up on this issue, I found that the file was being downloaded but it had problems being uploaded in the headless mode of FF.

**Comment by muskan6769** [comment]
@Monal5031 actually the problem was that the resume was not being uploaded because we were not able to make directories in media root as **permission denied error ** was being shown and therefore when the tests were running it was not finding an element with **collapseResumeFile** and hence the test was failing.

So if I just upload the resume directly to media directory then the test works perfectly as there is no need to create directories.
![s1](https://user-images.githubusercontent.com/34505804/49690254-ad1cc000-fb53-11e8-9897-a2b6490cb931.png)
![s2](https://user-images.githubusercontent.com/34505804/49690256-b4dc6480-fb53-11e8-8b2c-fea8ffec0879.png)

**Comment by Monal5031** [comment]
Nice digging @muskan6769 :tada: 
We can't directly add the resume to media directory and complete the test that would be something like asserting true with true :p, the test needs to check if there is no manipulation in between.
As per your comment, the directory is not being created due to permission errors <-- thus this is what we need to tackle in the patch.

**Comment by muskan6769** [comment]
@Monal5031 I had to use the following command to remove the permission errors
```sudo chmod -R 770 /home/muskan/Desktop/vms/vms/srv/``` to give permission to grp users to access media folders.
and now the test is successful.
![s3](https://user-images.githubusercontent.com/34505804/49700701-5ae9a680-fc08-11e8-8db4-2f62fad870ca.png)

**Comment by Monal5031** [comment]
770 is not too good to be given, 740 should be okay I guess. Go ahead and send a PR to uncomment the tests failing due to resume upload and change the permission to 740.

**Comment by muskan6769** [comment]
@Monal5031 if I change the file upload permissions and file upload directory permissions in settings.py then the error will be remove for the new users as when they first time upload the media files the srv folder will be created with correct permissions but for those whose media folder has already been created ,they need to run the command to change the permissions for the media folder.
